/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientController;
import java.awt.Image;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Vector;
import javax.swing.DefaultListModel;
import model.User;
import javax.swing.*;

/**
 *
 * @author Eman
 */
public class FriendListJFrame extends javax.swing.JFrame {

    
    ClientController clientController;
    User user;
    DefaultListModel dm=new DefaultListModel();
    DefaultListModel rdm=new DefaultListModel();

    public void setFriend(Vector<User> friend) {
        this.friend = friend;
    }
    
    Vector<User> friend;
    Vector<User> requestFriend=new Vector<>();

    public Vector<User> getRequestFriend() {
        return requestFriend;
    }
    
    //Set the friend request and paint it
    public void setRequestFriend(Vector<User> requestFriend) {
        this.requestFriend = requestFriend;
        
       
        
                
        requestFriendList();
        
    }
    
    public javax.swing.JList<User> friendjList1=new javax.swing.JList<>();
    
    public void paintList()
    {
        dm.clear();
        for(int i=0;i<friend.size();i++)
        {
            
            dm.addElement(friend.elementAt(i));
        }
       
        friendjList.setCellRenderer(new render());
     
        friendjList.setModel(dm);
    }
    public void requestFriendList()
    {
        rdm.clear();
        for(int i=0;i<requestFriend.size();i++)
        {
            
            rdm.addElement(requestFriend.elementAt(i));
        }
       
        requestjList.setCellRenderer(new RequestRender());
     
        requestjList.setModel(rdm);
    }
    /**
     * Creates new form FriendListJFrame
     */
    public FriendListJFrame(ClientController c,User u) {
        
        clientController=c;
        
        user=u;
        
        initComponents();
        
        friend=user.getFriends();
       //requestFriend=user.getRequestfriend();
        mainUsernameLabel.setText(user.getUsername());
        mainEmailLabel.setText(user.getEmail());
        this.setTitle("Hi Messenger");
        paintList();
         requestFriendList();
        
         ImageIcon logo=new ImageIcon(getClass().getResource("/view/logo.png"));
        this.setIconImage(logo.getImage());
       this.setVisible(true);
         
        
        /**
         * Adding window listener for action on close.
         */
        this.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
                
            }

            @Override
            public void windowClosing(WindowEvent e) {
                logOutMenuItem.doClick();
            }

            @Override
            public void windowClosed(WindowEvent e) {
                
            }

            @Override
            public void windowIconified(WindowEvent e) {
                
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
                
            }

            @Override
            public void windowActivated(WindowEvent e) {
                
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
               
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        statejComboBox = new javax.swing.JComboBox<>();
        addfriendButton = new javax.swing.JButton();
        chatGroupButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mainUsernameLabel = new javax.swing.JLabel();
        mainEmailLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        friendRequestTabbedPane = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        friendjList = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestjList = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        adLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        availableMenu = new javax.swing.JMenuItem();
        busyMenu = new javax.swing.JMenuItem();
        awayMenu = new javax.swing.JMenuItem();
        Options = new javax.swing.JMenu();
        chatgroupmenu = new javax.swing.JMenuItem();
        addfriendmenu = new javax.swing.JMenuItem();
        logOutMenuItem = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        aboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(52, 152, 219));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        jPanel2.setBackground(new java.awt.Color(52, 152, 219));

        statejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avaliable", "Busy", "Away" }));
        statejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statejComboBoxActionPerformed(evt);
            }
        });

        addfriendButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Add .png"))); // NOI18N
        addfriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfriendButtonActionPerformed(evt);
            }
        });

        chatGroupButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/groupChat.png"))); // NOI18N
        chatGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatGroupButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("User Name :");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/user.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("E-mail :");

        mainUsernameLabel.setText(" Mohamed Atef");

        mainEmailLabel.setText("atef123@gmail.com");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(statejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addfriendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mainUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mainUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(mainEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chatGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addfriendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statejComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        friendjList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friendjListMouseClicked(evt);
            }
        });
        friendjList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                friendjListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(friendjList);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );

        friendRequestTabbedPane.addTab("Friend List", jPanel5);

        requestjList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestjListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(requestjList);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        friendRequestTabbedPane.addTab("friend request", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(friendRequestTabbedPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(friendRequestTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        friendRequestTabbedPane.getAccessibleContext().setAccessibleName("Friend request");

        jPanel7.setBackground(new java.awt.Color(52, 152, 219));

        adLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ad.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Status");

        availableMenu.setText("Avaliable");
        availableMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableMenuActionPerformed(evt);
            }
        });
        jMenu1.add(availableMenu);

        busyMenu.setText("Busy");
        busyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busyMenuActionPerformed(evt);
            }
        });
        jMenu1.add(busyMenu);

        awayMenu.setText("Away");
        awayMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awayMenuActionPerformed(evt);
            }
        });
        jMenu1.add(awayMenu);

        jMenuBar1.add(jMenu1);

        Options.setText("Options");
        Options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionsActionPerformed(evt);
            }
        });

        chatgroupmenu.setText("New Chat Group");
        chatgroupmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatgroupmenuActionPerformed(evt);
            }
        });
        Options.add(chatgroupmenu);

        addfriendmenu.setText("Add Friend");
        addfriendmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfriendmenuActionPerformed(evt);
            }
        });
        Options.add(addfriendmenu);

        logOutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        logOutMenuItem.setText("Sign Out");
        logOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutMenuItemActionPerformed(evt);
            }
        });
        Options.add(logOutMenuItem);

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        Options.add(exitMenu);

        jMenuBar1.add(Options);

        help.setText("Help");

        aboutUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        aboutUs.setText("About Us");
        aboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsActionPerformed(evt);
            }
        });
        help.add(aboutUs);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void availableMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableMenuActionPerformed
        
        statejComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_availableMenuActionPerformed

    private void requestjListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestjListMouseClicked
       
         if(evt.getClickCount()==2){ 
             User friendIdreq=requestjList.getSelectedValue();   
             String userName = friendIdreq.getUsername();
       
       
       
                if(userName != null)
                 {
          
                    int res= JOptionPane.showConfirmDialog(this, "Do You want to accept a friend request from "+userName,"New Friend Request",JOptionPane.YES_NO_OPTION);
           
                    if(res==JOptionPane.YES_OPTION)
                    {
                           
                            if(clientController.addFriends(friendIdreq.getId())){
                            
                                System.out.println("friends was added successfully");
                                //clientController.updateFriendRequest(friend);
                                
                                
                            }else{
                                System.out.println("add was failled");
                                //clientController.updateFriendRequest(friend);
                            }
                    }
                    if(res==JOptionPane.NO_OPTION)
                    {
                        System.out.println("no");
                        clientController.removeFriendRequest(friendIdreq.getId());
                        //clientController.removeFriendRequest(user.getId());
                        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    }
                   }
       
        
         }
        
    }//GEN-LAST:event_requestjListMouseClicked

    private void friendjListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_friendjListValueChanged
       
               
    }//GEN-LAST:event_friendjListValueChanged

    private void friendjListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friendjListMouseClicked
  
        if(evt.getClickCount()==2){
            
             User obj= (User)friendjList.getSelectedValue();
             clientController.open(obj);
        
        }
   /* User obj= (User)friendjList.getSelectedValue();
     clientController.open(obj);*/
        
    
      
        
    }//GEN-LAST:event_friendjListMouseClicked

    private void statejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statejComboBoxActionPerformed
        
       switch(statejComboBox.getSelectedIndex()){
       
           case 0:
               user.setState(User.Available);
               //clientController.updateState(User.Available);
               clientController.changeMyState(User.Available);
               break;
           case 1:
               user.setState(User.Busy);
               //clientController.updateState(User.Away);
               clientController.changeMyState(User.Busy);
               break;
           case 2:
               user.setState(User.Away);
               //clientController.updateState(User.Away);
               clientController.changeMyState(User.Away);
               break;
               
       
       }
        
        
    }//GEN-LAST:event_statejComboBoxActionPerformed

    private void OptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionsActionPerformed
        
       
    }//GEN-LAST:event_OptionsActionPerformed

    private void logOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutMenuItemActionPerformed
         
        clientController.setMeOffline();
        this.dispose();
        
    }//GEN-LAST:event_logOutMenuItemActionPerformed

    private void addfriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfriendButtonActionPerformed
     
        boolean validateRes , requestRes;
        String  userName ;
        String email =JOptionPane.showInputDialog(this,"Please enter The email .","Add Friend",JOptionPane.OK_CANCEL_OPTION);
       
        userName = clientController.searchEmail(email);
        if(email == null)
        {
           setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
        } 
        
        else
        {
            
            friend = user.getFriends();
            for(User f : friend)
            {
                if(f.getEmail().equals(email))
               {
                JOptionPane.showMessageDialog(this,"That is already a friend of You .");
               }
            }    
               if(user.getEmail().equals(email))
               {
                JOptionPane.showMessageDialog(this," You can't send a request to yourself .");
               } 
               
               else
               {
                    validateRes = model.Validator.isEmail(email);
                    if(validateRes == true)
                    {
                        
                       requestRes = clientController.addFriendRequest(user.getId(), email);
          
                      
                    }
                    else
                    {
                        JOptionPane.showConfirmDialog(this, "The Email is wrong .");
                    } 
               }
        }
        
        
      
    }//GEN-LAST:event_addfriendButtonActionPerformed

    private void chatGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatGroupButtonActionPerformed
      
        clientController.selectChatGroup();
    }//GEN-LAST:event_chatGroupButtonActionPerformed

    private void addfriendmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfriendmenuActionPerformed
        addfriendButton.doClick();
    }//GEN-LAST:event_addfriendmenuActionPerformed

    private void chatgroupmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatgroupmenuActionPerformed
        // TODO add your handling code here:
        chatGroupButton.doClick();
    }//GEN-LAST:event_chatgroupmenuActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        // TODO add your handling code here:
        logOutMenuItem.doClick();
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed

    private void busyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busyMenuActionPerformed
       statejComboBox.setSelectedIndex(1);
    }//GEN-LAST:event_busyMenuActionPerformed

    private void awayMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awayMenuActionPerformed
        statejComboBox.setSelectedIndex(2);
    }//GEN-LAST:event_awayMenuActionPerformed

    private void aboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsActionPerformed
       new aboutUs();
    }//GEN-LAST:event_aboutUsActionPerformed

   public ImageIcon imageAd;
   static int index=0;
public void setAd()
{
    index++;
    //imageAd=new ImageIcon("ad"+index+".png").getImage().getScaledInstance(300, 100, Image.SCALE_SMOOTH);
  adLabel.setIcon(new ImageIcon( new ImageIcon("ad"+index+".png").getImage().getScaledInstance(510, 200, Image.SCALE_SMOOTH)));  
} 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Options;
    private javax.swing.JMenuItem aboutUs;
    private javax.swing.JLabel adLabel;
    private javax.swing.JButton addfriendButton;
    private javax.swing.JMenuItem addfriendmenu;
    private javax.swing.JMenuItem availableMenu;
    private javax.swing.JMenuItem awayMenu;
    private javax.swing.JMenuItem busyMenu;
    private javax.swing.JButton chatGroupButton;
    private javax.swing.JMenuItem chatgroupmenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JTabbedPane friendRequestTabbedPane;
    private javax.swing.JList<Object> friendjList;
    private javax.swing.JMenu help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem logOutMenuItem;
    private javax.swing.JLabel mainEmailLabel;
    private javax.swing.JLabel mainUsernameLabel;
    private javax.swing.JList<User> requestjList;
    private javax.swing.JComboBox<String> statejComboBox;
    // End of variables declaration//GEN-END:variables
}
